
import 'dart:ui';

class ColorList {
  final colorSelectList = [
    const Color(0xffff7f7f),
    const Color(0xffff7fff),
    const Color(0xff7f7fff),
    const Color(0xff7fffff),
    const Color(0xff7fff7f),
    const Color(0xffffff7f),
    const Color(0xffff9393),
    const Color(0xffff93ff),
    const Color(0xff9393ff),
    const Color(0xff93ffff),
    const Color(0xff93ff93),
    const Color(0xffffff93),
    const Color(0xffffadad),
    const Color(0xffffadff),
    const Color(0xffadadff),
    const Color(0xffadffff),
    const Color(0xffadffad),
    const Color(0xffffffad),
    const Color(0xffffc6c6),
    const Color(0xffffc6ff),
    const Color(0xffc6c6ff),
    const Color(0xffc6ffff),
    const Color(0xffc6ffc6),
    const Color(0xffffffc6),
    const Color(0xffff7fbf),
    const Color(0xffbf7fff),
    const Color(0xff7fbfff),
    const Color(0xff7fffbf),
    const Color(0xffbfff7f),
    const Color(0xffffbf7f),
    const Color(0xffff93c9),
    const Color(0xffc993ff),
    const Color(0xff93c9ff),
    const Color(0xff93ffc9),
    const Color(0xffc9ff93),
    const Color(0xffffc993),
    const Color(0xffffadd6),
    const Color(0xffd6adff),
    const Color(0xffadd6ff),
    const Color(0xffadffd6),
    const Color(0xffd6ffad),
    const Color(0xffffd6ad),
    const Color(0xffffc6e2),
    const Color(0xffe2c6ff),
    const Color(0xffc6e2ff),
    const Color(0xffc6ffe2),
    const Color(0xffe2ffc6),
    const Color(0xffffe2c6),
  ];
}
